### ISSUE TITLE
Registration of new users broken

### ISSUE THREAD

**Issue by 5gbr** [ffgraz/manman#1]
When trying to register a new user via https://manman.ffgraz.net/person/register the website is doing nothing after clicking Create. (aside from the password disappearing)

**Comment by mkg20001** [comment]
It seems to  trigger this codepath (the else part)

https://github.com/ffgraz/manman/blob/funkfeuer/app/controllers/person_controller.rb#L100-L107

Likely a validation error coming from person.rb

Also see #2, which may be a problem
